/** Single entry point for UI icons: the set is part of the identity, so swap it here and nowhere else. */
import type { IconWeight } from '@phosphor-icons/react'

export type { Icon as AppIcon, IconWeight } from '@phosphor-icons/react'
export {
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowsClockwise as RefreshCw,
	ArrowsDownUp as ArrowUpDown,
	ArrowUp,
	ArrowUpRight,
	Bell,
	BellSlash as BellOff,
	CaretDown as ChevronDown,
	CaretLeft as ChevronLeft,
	CaretRight as ChevronRight,
	ChatCircle as MessageSquare,
	Check,
	CheckCircle,
	Circle,
	CircleNotch as Spinner,
	Clock,
	Copy,
	DotsSixVertical as GripVertical,
	Envelope as Mail,
	Eye,
	EyeSlash as EyeOff,
	FileText,
	Gauge as LayoutDashboard,
	Gear as Settings,
	House as Home,
	Info,
	Key,
	Lightbulb,
	List as Menu,
	ListChecks as ListTodo,
	MagnifyingGlass as Search,
	Monitor,
	Moon,
	PaperPlaneRight as SendHorizontal,
	PaperPlaneTilt as Send,
	PencilSimple as Pencil,
	Plus,
	Shield,
	SignOut as LogOut,
	SpeakerHigh as Volume,
	SpeakerSlash as VolumeOff,
	SquaresFour as LayoutGrid,
	Sun,
	Trash,
	TrendUp as TrendingUp,
	User,
	UserGear as UserCog,
	Users,
	Warning as AlertTriangle,
	WarningCircle as AlertCircle,
	WebhooksLogo as Webhook,
	WifiSlash as WifiOff,
	X,
} from '@phosphor-icons/react'

/** Suave draws icons in Phosphor "regular" and marks the active nav item with "fill". */
export const ICON_WEIGHT: IconWeight = 'regular'
export const ACTIVE_ICON_WEIGHT: IconWeight = 'fill'
